// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: gateways.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Gateways struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrentlyConnected  string   `protobuf:"bytes,1,opt,name=currently_connected,json=currentlyConnected,proto3" json:"currently_connected,omitempty"`
	AvailableGateways   []string `protobuf:"bytes,2,rep,name=available_gateways,json=availableGateways,proto3" json:"available_gateways,omitempty"`
	AvailableGatewaysId []string `protobuf:"bytes,3,rep,name=available_gateways_id,json=availableGatewaysId,proto3" json:"available_gateways_id,omitempty"`
}

func (x *Gateways) Reset() {
	*x = Gateways{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateways_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gateways) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gateways) ProtoMessage() {}

func (x *Gateways) ProtoReflect() protoreflect.Message {
	mi := &file_gateways_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gateways.ProtoReflect.Descriptor instead.
func (*Gateways) Descriptor() ([]byte, []int) {
	return file_gateways_proto_rawDescGZIP(), []int{0}
}

func (x *Gateways) GetCurrentlyConnected() string {
	if x != nil {
		return x.CurrentlyConnected
	}
	return ""
}

func (x *Gateways) GetAvailableGateways() []string {
	if x != nil {
		return x.AvailableGateways
	}
	return nil
}

func (x *Gateways) GetAvailableGatewaysId() []string {
	if x != nil {
		return x.AvailableGatewaysId
	}
	return nil
}

type ConnectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GatewayName string `protobuf:"bytes,1,opt,name=gateway_name,json=gatewayName,proto3" json:"gateway_name,omitempty"`
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateways_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateways_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_gateways_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectRequest) GetGatewayName() string {
	if x != nil {
		return x.GatewayName
	}
	return ""
}

type GetGateways struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gateways *Gateways `protobuf:"bytes,1,opt,name=Gateways,proto3" json:"Gateways,omitempty"`
}

func (x *GetGateways) Reset() {
	*x = GetGateways{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateways_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGateways) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGateways) ProtoMessage() {}

func (x *GetGateways) ProtoReflect() protoreflect.Message {
	mi := &file_gateways_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGateways.ProtoReflect.Descriptor instead.
func (*GetGateways) Descriptor() ([]byte, []int) {
	return file_gateways_proto_rawDescGZIP(), []int{2}
}

func (x *GetGateways) GetGateways() *Gateways {
	if x != nil {
		return x.Gateways
	}
	return nil
}

var File_gateways_proto protoreflect.FileDescriptor

var file_gateways_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9e,
	0x01, 0x0a, 0x08, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x73, 0x12, 0x2f, 0x0a, 0x13, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x6c, 0x79, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x6c, 0x79, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x2d, 0x0a, 0x12,
	0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x11, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61,
	0x62, 0x6c, 0x65, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x73, 0x12, 0x32, 0x0a, 0x15, 0x61,
	0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x73, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x13, 0x61, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x73, 0x49, 0x64, 0x22,
	0x33, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x21, 0x0a, 0x0c, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0x34, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x47, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x73, 0x12, 0x25, 0x0a, 0x08, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x73,
	0x52, 0x08, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x73, 0x32, 0x7f, 0x0a, 0x03, 0x56, 0x70,
	0x6e, 0x12, 0x20, 0x0a, 0x08, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x73, 0x12, 0x06, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0c, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x73, 0x12, 0x2d, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x0f,
	0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0f, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x30, 0x01, 0x12, 0x27, 0x0a, 0x0a, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0f, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x69, 0x63, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x30, 0x01, 0x42, 0x29, 0x5a, 0x27, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x68, 0x79, 0x6f, 0x64, 0x75,
	0x6f, 0x75, 0x2f, 0x6e, 0x6f, 0x72, 0x64, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2d, 0x68, 0x65, 0x6c,
	0x70, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gateways_proto_rawDescOnce sync.Once
	file_gateways_proto_rawDescData = file_gateways_proto_rawDesc
)

func file_gateways_proto_rawDescGZIP() []byte {
	file_gateways_proto_rawDescOnce.Do(func() {
		file_gateways_proto_rawDescData = protoimpl.X.CompressGZIP(file_gateways_proto_rawDescData)
	})
	return file_gateways_proto_rawDescData
}

var file_gateways_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gateways_proto_goTypes = []interface{}{
	(*Gateways)(nil),       // 0: Gateways
	(*ConnectRequest)(nil), // 1: ConnectRequest
	(*GetGateways)(nil),    // 2: GetGateways
	(*Empty)(nil),          // 3: Empty
	(*GenericPayload)(nil), // 4: GenericPayload
}
var file_gateways_proto_depIdxs = []int32{
	0, // 0: GetGateways.Gateways:type_name -> Gateways
	3, // 1: Vpn.Gateways:input_type -> Empty
	1, // 2: Vpn.Connect:input_type -> ConnectRequest
	3, // 3: Vpn.Disconnect:input_type -> Empty
	2, // 4: Vpn.Gateways:output_type -> GetGateways
	4, // 5: Vpn.Connect:output_type -> GenericPayload
	4, // 6: Vpn.Disconnect:output_type -> GenericPayload
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gateways_proto_init() }
func file_gateways_proto_init() {
	if File_gateways_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_gateways_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gateways); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateways_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateways_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGateways); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gateways_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateways_proto_goTypes,
		DependencyIndexes: file_gateways_proto_depIdxs,
		MessageInfos:      file_gateways_proto_msgTypes,
	}.Build()
	File_gateways_proto = out.File
	file_gateways_proto_rawDesc = nil
	file_gateways_proto_goTypes = nil
	file_gateways_proto_depIdxs = nil
}
