# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master", "preview" ]
  pull_request:
    branches: [ "master", "preview" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Setup dependencies
      run: sudo apt-get install -y make gcc libgtk-3-dev libayatana-appindicator3-dev protobuf-compiler && go install github.com/golang/protobuf/protoc-gen-go@latest

    - name: Build
      run: make build
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: nordlayer-helper

